name: Deploy Logic App
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
            az deployment group create \
              --resource-group my-resource-group \
              --template-file ./my-template.json \
              --parameters ./my-parameters.json 
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
