name: Deploy Logic App
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy ARM template
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
            az deployment group create \
              --resource-group my-resource-group \
              --template-file ./my-template.json \
              --parameters ./my-parameters.json 
        env:
          AZURE_SUBSCRIPTION_ID: '2c00645e-fad1-46f3-ba18-904edde8736c'
          AZURE_TENANT_ID: '08fdfb44-3c18-4aa7-9519-72bddc98ad3a'
          AZURE_CLIENT_ID: '7a61cb8d-89eb-4118-be74-011035efa4bf'
          AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
