name: Authenticate-Azure-Portal
'on':
  workflow_dispatch: null
jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
