name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: Hello Github
        required: true
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ inputs.message }}"
