name: My Workflow
'on':
  workflow_call:
    inputs:
      message:
      description: The message to display
      required: true
    
jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display Message
        env:
          SECRET_KEY: '${{ secrets.SECRET_MAGIC }}'
        run: |
          echo ${{ inputs.message }}
          echo $SECRET_KEY
