name: resuable workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Pipeline-to-Secret workflow
        uses: Github-actions/.github/workflows/workflow-P.yml@main
        with:
          secret-value: ${{ secrets.SECRET_MAGIC }}
