name: Pipeline-to-Secret
'on':
  push:
    branches:
      - main
jobs:
  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Running secrets
        env:
          DEVOPS: '${{ secrets.SECRET_MAGIC }}'
        run: |
          if [ "$DEVOPS" == "DevOps Training" ]
          then
            echo "Secret opened"
          fi
