name: Pipeline-to-Secret
'on': Push
jobs:
  default-env-variables: null
  runs-on: ubuntu-latest
  steps:
    - name: Running secrets
      run: |
        if [ "$DEVOPS"=="DevOps Training" ]
        then
         echo "Secret opened"
        fi
        env:
        DEVOPS: ${{ secrets.SECRET_MAGIC }}
