name: Call a reusable workflow

'on':
  workflow_dispatch

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: varsha-disys/github-actions/.github/workflows/workflow_b.yml@main
    with:
      config-path: .github/labeler.yml
    
