name: Example Workflow
'on':
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: >-
          echo "Input value is ${{ inputs.input_name }} and secret value is ${{
          secrets.secret_name }}"
inputs:
  input_name:
    description: Description of the input
  another_input:
    description: Another input description
secrets:
  secret_name:
    description: Description of the secret
