name: Call a reusable workflow
'on':
  pull_request:
    branches:
      - main
jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Varsha-DISYS/Github-actions/.github/workflows/workflow_b.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: '${{ secrets.SECRET_MAGIC }}'
