name: resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: varsha-disys/github-actions/.github/workflows/workflow_b.yml@main
    with:
      username: Varsha
    secrets:
      token: ${{ secrets.SECRET_MAGIC }}

