name: Example Workflow
'on':
  workflow_call:
        inputs: 
          input_name:
          description: Description of the input
        secrets:
          secret_name:
          description: Description of the secret
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: >-
          echo "Input value is ${{ inputs.input_name }} and secret value is ${{
          secrets.SECRET_MAGIC }}"
